package com.ylzinfo.dao.mappers;

import com.ylzinfo.dao.entity.MmpRouteConfig;

import java.util.List;

public interface MmpRouteConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmp_route_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmp_route_config
     *
     * @mbg.generated
     */
    int insert(MmpRouteConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmp_route_config
     *
     * @mbg.generated
     */
    MmpRouteConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmp_route_config
     *
     * @mbg.generated
     */
    List<MmpRouteConfig> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmp_route_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MmpRouteConfig record);

    /**
     * 根据appid和医疗机构编码查询配置信息
     *
     * @param appId
     * @param medOrgNo
     * @return
     */
    MmpRouteConfig selectByMedOrgNo(String appId, String medOrgNo);

    /**
     * 根据appId查询配置信息
     *
     * @param appId
     * @return
     */
    MmpRouteConfig selectByAppId(String appId);
}