package com.demo.dao.mappers;

import com.demo.dao.entity.GirlsInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface GirlsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girls_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girls_info
     *
     * @mbg.generated
     */
    int insert(GirlsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girls_info
     *
     * @mbg.generated
     */
    GirlsInfo selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girls_info
     *
     * @mbg.generated
     */
    List<GirlsInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girls_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GirlsInfo record);
}