#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.ylzinfo.dao.entity
  mapperLocations: classpath:/dao/*.xml



---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://192.168.44.90:3306/mmp_route?serverTimezone=UTC
    username: root
    password: ylz@yhkj#2020
    driver-class-name: com.mysql.jdbc.Driver

logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug